const fs = require('fs');
const path = require('path');

const en = {
    "Metadata": {"title": "Eilat Booking Premium - Luxury Vacations in Eilat","description": "Book your next vacation in Eilat at the most luxurious holiday apartments."},
    "Navigation": {"home": "Home","apartments": "Apartments","hotels": "Luxury Hotels","villas": "Villas","experiences": "Experiences","magazine": "Magazine","vip": "VIP Services","about": "About","contact": "Contact","search": "Search","accessibility": "Accessibility","profile": "Profile"},
    "Hero": {"title": "Luxury Hospitality in Eilat","subtitle": "Exclusive holiday apartments in prime locations","cta": "Book Now"},
    "Featured": {"title": "Our Featured Properties","subtitle": "Choose from our exclusive collection for the perfect vacation","night": "night","book": "Book Now","details": "More Details","guests": "Guests","rooms": "Rooms","recommended": "Recommended"},
    "Property": {"about": "About Property","location": "Location","waze": "Navigate with Waze","amenities": "Amenities","guests": "Guests","guests_max": "Max","rooms": "Rooms","bedrooms": "Bedrooms","per_night": "Per Night","book_now": "Book Now","total_price": "Total Price","taxes": "Including taxes and fees","not_charged": "You won't be charged yet"},
    "Checkout": {"title": "Secure Checkout","confirm": "Confirm & Pay","booking_for": "Your booking for","dates": "Dates","guests": "Guests","total": "Total to pay","service_fee": "Service Fee","back": "Back"},
    "Payment": {"card_name": "Cardholder Name","card_number": "Card Number","expiry": "Expiry","cvc": "CVC","pay": "Pay","processing": "Processing...","success_title": "Payment Successful!","success_msg": "Your booking is confirmed. A receipt has been sent.","secure": "SSL Secure Payment","or_card": "Or pay with card"},
    "Search": {"title": "Search Results","view_all": "View All"},
    "Categories": {"title": "Vacations by Category","hotels": "Luxury Hotels","apartments": "Holiday Apartments","villas": "Exclusive Villas","attractions": "Attractions","vacation": "Vacation"},
    "Home": {"hotels_title": "Luxury Hotels","villas_title": "Exclusive Villas","apartments_title": "Holiday Apartments","recommended_title": "Our Recommendations","view_all": "View All"},
    "SearchForm": {"property_type": "Property Type","location": "Location","dates": "Dates","guests": "Guests","search_btn": "Search","check_in": "Check In","check_out": "Check Out","select_dates": "Select Dates","confirm": "Confirm","close": "Close","ai_mode": "Smart AI Search","standard_mode": "Standard Search","ai_placeholder": "Describe your dream vacation... (e.g., 'Luxury villa for 10 people with pool')","thinking": "Thinking...","magic_search": "Magic Search","types": {"all": "All","hotel": "Hotels","apartment": "Apartments","villa": "Villas"}},
    "Auth": {"login_title": "Welcome Back","login_subtitle": "Login to your account","register_title": "Join Eilat Luxury","register_subtitle": "Choose your account type","email": "Email","password": "Password","full_name": "Full Name","login_btn": "Sign In","register_btn": "Create Account","no_account": "Don't have an account?","has_account": "Already have an account?","sign_up": "Sign Up","login": "Login","role_guest": "I want to book","role_host": "I want to host","role_guest_desc": "Customer","role_host_desc": "Business Owner","welcome": "Hello","logout": "Logout","my_account": "My Account","business_dashboard": "Business Dashboard","admin_panel": "Admin Panel","login_link": "Login","account_menu_label": "Account Login","login_gateway_title": "Who are you?","login_gateway_subtitle": "Choose your login type","login_admin_title": "Admin Login","login_admin_subtitle": "Access Admin Panel","login_host_title": "Host Login","login_host_subtitle": "Manage your properties","login_customer_title": "Customer Login","login_customer_subtitle": "View your bookings","list_asset": "List Property"},
    "Host": {"hero_title": "Join Our Hosts","hero_subtitle": "Turn your property into Eilat's next top destination. Open the door to luxury bookings.","form_title": "Start your journey","form_subtitle": "Fill in the details and we will contact you within 24 hours.","first_name": "First Name","last_name": "Last Name","property_type": "Property Type","phone": "Phone","submit": "Submit Request","benefits": {"earn_title": "Earn More","earn_desc": "Keep up to 90% of your revenue with our low fees.","protection_title": "Full Protection","protection_desc": "Host insurance worth 1,000,000 NIS per booking.","guests_title": "Quality Guests","guests_desc": "We attract a high-quality audience looking for luxury.","manage_title": "Easy Management","manage_desc": "Advanced AI system to manage everything easily."},"types": {"villa": "Luxury Villa","penthouse": "Penthouse","hotel": "Boutique Hotel","other": "Other"},"add_property_title": "Add New Property","add_property_subtitle": "Fill in the details to publish your property","basic_info": "General Details","property_title": "Property Title","price_per_night": "Price per night","description": "Property Description","photos": "Photos","upload_click": "Upload Photos","cancel": "Cancel","publish": "Publish Property","processing": "Saving..."},
    "Footer": {"quick_links": "Quick Links","support": "Support & Account","contact_us": "Contact Us","newsletter_placeholder": "Your Email...","newsletter_btn": "Subscribe","rights": "All rights reserved."},
    "Accessibility": {"enlarge_text": "Enlarge Text","decrease_text": "Decrease Text","high_contrast": "High Contrast","monochrome": "Monochrome","readable_font": "Readable Font","highlight_links": "Highlight Links","stop_animations": "Stop Animations","reset": "Reset Settings"},
    "Cart": {"title": "Your Cart","empty": "Cart is empty","sold_out": "Sold Out!","per_night": "Night","view_property": "View Property","total": "Total:","proceed": "Proceed to Checkout","clear": "Clear Cart","added": "Added","save_later": "Save for Later"},
    "Deals": {"last_minute": "Up to 25% discount for upcoming weekend!"},
    "Experiences": {"title": "Unforgettable Experiences","subtitle": "Your vacation is much more than sleep. We've collected the best attractions and experiences in Eilat, at exclusive prices for our guests."},
    "OnlineChat": {"live_chat": "Live Chat","voice_on": "Voice On","voice_off": "Voice Off","stop_audio": "Stop Audio","whatsapp": "Move to WhatsApp","call_management": "Call Management"},
    "Calendar": {"next": "Next","previous": "Previous","today": "Today","month": "Month","week": "Week","day": "Day"},
    "Reviews": {"name_placeholder": "Your name...","review_placeholder": "Tell us how your vacation was...","submit": "Submit Review"}
};

const he = {
    ...en,
    "Metadata": {"title": "אילת בוקינג פרימיום - חופשות יוקרה באילת","description": "הזמינו את החופשה הבאה שלכם באילת בדירות הנופש היוקרתיות ביותר."},
    "Navigation": {"home": "דף הבית","apartments": "דירות נופש","hotels": "מלונות יוקרה","villas": "וילות","experiences": "חוויות","magazine": "מגזין","vip": "שירותי VIP","about": "אודות","contact": "צור קשר","search": "חיפוש","accessibility": "נגישות","profile": "פרופיל"},
    "Hero": {"title": "חווית אירוח יוקרתית באילת","subtitle": "דירות נופש אקסקלוסיביות במיקומים הטובים ביותר","cta": "הזמן עכשיו"},
    "Featured": {"title": "הדירות הנבחרות שלנו","subtitle": "בחרו מתוך קולקציית הדירות היוקרתית שלנו לחופשה המושלמת","night": "לילה","book": "הזמן עכשיו","details": "פרטים נוספים","guests": "אורחים","rooms": "חדרים","recommended": "מומלץ"},
    "Property": {"about": "על הנכס","location": "מיקום","waze": "נווט עם Waze","amenities": "שירותים ומתקנים","guests": "אורחים","guests_max": "מקסימום","rooms": "חדרים","bedrooms": "חדרי שינה","per_night": "ללילה","book_now": "הזמן עכשיו","total_price": "מחיר סה\"כ","taxes": "כולל מיסים ועמלות","not_charged": "לא תחויב עדיין"},
    "Checkout": {"title": "תשלום מאובטח","confirm": "אישור ותשלום","booking_for": "ההזמנה שלך עבור","dates": "תאריכים","guests": "אורחים","total": "סה\"כ לתשלום","service_fee": "דמי שירות","back": "חזור"},
    "Payment": {"card_name": "שם בעל הכרטיס","card_number": "מספר כרטיס","expiry": "תוקף","cvc": "CVC","pay": "שלם","processing": "מעבד נתונים...","success_title": "התשלום בוצע בהצלחה!","success_msg": "ההזמנה שלך אושרה. אישור נשלח למייל.","secure": "תשלום מאובטח SSL","or_card": "או שלם באשראי"},
    "Search": {"title": "תוצאות חיפוש","view_all": "צפה בהכל"},
    "Categories": {"title": "חופשה לפי קטגוריה","hotels": "מלונות יוקרה","apartments": "דירות נופש","villas": "וילות אקסקלוסיביות","attractions": "אטרקציות","vacation": "חופש"},
    "Home": {"hotels_title": "מלונות יוקרה","villas_title": "וילות אקסקלוסיביות","apartments_title": "דירות נופש","recommended_title": "המומלצים שלנו","view_all": "הצג הכל"},
    "SearchForm": {"property_type": "סוג הנכס","location": "מיקום","dates": "תאריכים","guests": "אורחים","search_btn": "חפש חופשה","check_in": "צ'ק-אין","check_out": "צ'ק-אאוט","select_dates": "בחר תאריכים","confirm": "אישור","close": "סגור","ai_mode": "חיפוש AI חכם","standard_mode": "חיפוש רגיל","ai_placeholder": "תאר את חופשת החלומות שלך... (למשל: 'וילה יוקרתית ל-10 אנשים עם בריכה')","thinking": "חושב...","magic_search": "חיפוש קסם","types": {"all": "הכל","hotel": "מלונות","apartment": "דירות","villa": "וילות"}},
    "Auth": {"login_title": "ברוך שובך","login_subtitle": "התחבר לחשבון שלך","register_title": "הצטרף לאילת לקז'רי","register_subtitle": "בחר את סוג החשבון שלך","email": "אימייל","password": "סיסמא","full_name": "שם מלא","login_btn": "התחבר","register_btn": "צור חשבון","no_account": "אין לך חשבון?","has_account": "כבר יש לך חשבון?","sign_up": "הירשם","login": "התחבר","role_guest": "אני רוצה להזמין חופשה","role_host": "אני רוצה לפרסם נכס","role_guest_desc": "לקוח","role_host_desc": "בעל עסק","welcome": "שלום","logout": "התנתק","my_account": "החשבון שלי","business_dashboard": "לוח בקרה עסקי","admin_panel": "ניהול ראשי","login_link": "התחברות","account_menu_label": "כניסה לחשבון","login_gateway_title": "מי אתה?","login_gateway_subtitle": "בחר את סוג הכניסה שלך","login_admin_title": "כניסת מנהל","login_admin_subtitle": "גישה לאזור הניהול","login_host_title": "כניסת בעל עסק","login_host_subtitle": "נהל את הנכסים שלך","login_customer_title": "כניסת לקוח","login_customer_subtitle": "צפה בהזמנות שלך","list_asset": "פרסם נכס"},
    "Host": {"hero_title": "הצטרף לנבחרת המארחים","hero_subtitle": "הפוך את הנכס שלך ליעד המבוקש הבא באילת. פתח דלת להזמנות יוקרה.","form_title": "התחל את המסע שלך","form_subtitle": "מלא את הפרטים ונחזור אליך תוך 24 שעות.","first_name": "שם פרטי","last_name": "שם משפחה","property_type": "סוג הנכס","phone": "טלפון","submit": "שלח בקשה","benefits": {"earn_title": "הרווח יותר","earn_desc": "שמור עד 90% מההכנסות שלך עם העמלות הנמוכות שלנו.","protection_title": "הגנה מלאה","protection_desc": "ביטוח מארחים בשווי 1,000,000 ש\"ח בכל הזמנה.","guests_title": "אורחים איכותיים","guests_desc": "אנחנו מושכים קהל איכותי שמחפש יוקרה.","manage_title": "ניהול קל","manage_desc": "מערכת AI מתקדמת לניהול הכל בקלות."},"types": {"villa": "וילת יוקרה","penthouse": "פנטהאוז","hotel": "מלון בוטיק","other": "אחר"},"add_property_title": "הוספת נכס חדש","add_property_subtitle": "מלא את הפרטים כדי לפרסם את הנכס שלך","basic_info": "פרטים כלליים","property_title": "כותרת הנכס","price_per_night": "מחיר ללילה","description": "תיאור הנכס","photos": "תמונות","upload_click": "העלאת תמונות","cancel": "ביטול","publish": "פרסם נכס","processing": "שומר..."},
    "Footer": {"quick_links": "קישורים מהירים","support": "איזור אישי ותמיכה","contact_us": "יצירת קשר","newsletter_placeholder": "האימייל שלך...","newsletter_btn": "הירשם לניוזלטר","rights": "כל הזכויות שמורות."},
    "Accessibility": {"enlarge_text": "הגדלת טקסט","decrease_text": "הקטנת טקסט","high_contrast": "ניגודיות גבוהה","monochrome": "מונוכרום (אפור)","readable_font": "גופן קריא","highlight_links": "הדגשת קישורים","stop_animations": "עצירת אנימציות","reset": "איפוס הגדרות"},
    "Cart": {"title": "העגלה שלך","empty": "העגלה ריקה","sold_out": "כבר לא זמין!","per_night": "לילה","view_property": "צפה בנכס","total": "סה\"כ:","proceed": "המשך לתשלום","clear": "רוקן עגלה","added": "נוסף לעגלה","save_later": "שמור לאחר כך"},
    "Deals": {"last_minute": "עד 25% הנחה להזמנות לסופ\"ש הקרוב!"},
    "Experiences": {"title": "חוויות בלתי נשכחות","subtitle": "החופשה שלכם היא הרבה מעבר לשינה. אספנו עבורכם את האטרקציות והחוויות הכי שוות באילת, במחירים בלעדיים לאורחי האתר."},
    "OnlineChat": {"live_chat": "צ'אט אונליין","voice_on": "הפעלת קול","voice_off": "כיבוי קול","stop_audio": "השתק שמע","whatsapp": "העבר לוואטסאפ","call_management": "צור קשר עם ההנהלה"},
    "Calendar": {"next": "הבא","previous": "הקודם","today": "היום","month": "חודש","week": "שבוע","day": "יום"},
    "Reviews": {"name_placeholder": "השם שלך...","review_placeholder": "ספר לנו איך הייתה החופשה...","submit": "שלח תגובה"}
};

const ru = {
    ...en,
    "Metadata": {"title": "Eilat Booking Premium - Элитный отдых в Эйлате","description": "Забронируйте свой следующий отпуск в Эйлате в самых роскошных апартаментах."},
    "Navigation": {"home": "Главная","apartments": "Апартаменты","hotels": "Отели","villas": "Виллы","experiences": "Впечатления","magazine": "Журнал","vip": "VIP-услуги","about": "О нас","contact": "Контакты","search": "Поиск","accessibility": "Доступность","profile": "Профиль"},
    "Hero": {"title": "Роскошное гостеприимство в Эйлате","subtitle": "Эксклюзивные апартаменты в лучших районах","cta": "Бронируйте сейчас"},
    "Featured": {"title": "Наши лучшие объекты","subtitle": "Выберите из нашей эксклюзивной коллекции для идеального отдыха","night": "ночь","book": "Бронировать","details": "Подробнее","guests": "Гости","rooms": "Номера","recommended": "Рекомендуемые"},
    "Property": {"about": "Об объекте","location": "Расположение","waze": "Навигация в Waze","amenities": "Удобства","guests": "Гости","guests_max": "Максимум","rooms": "Номера","bedrooms": "Спальни","per_night": "За ночь","book_now": "Бронировать сейчас","total_price": "Общая цена","taxes": "Включая налоги","not_charged": "Оплата не взимается"},
    "Checkout": {"title": "Безопасная оплата","confirm": "Подтвердить и оплатить","booking_for": "Ваше бронирование","dates": "Даты","guests": "Гости","total": "К оплате","service_fee": "Сервисный сбор","back": "Назад"},
    "Payment": {"card_name": "Имя на карте","card_number": "Номер карты","expiry": "Срок действия","cvc": "CVC","pay": "Оплатить","processing": "Обработка...","success_title": "Оплата прошла успешно!","success_msg": "Ваше бронирование подтверждено.","secure": "Безопасный платеж SSL","or_card": "Или оплатить картой"},
    "Search": {"title": "Результаты поиска","view_all": "Смотреть все"},
    "Categories": {"title": "Отдых по категориям","hotels": "Роскошные отели","apartments": "Апартаменты","villas": "Виллы","attractions": "Аттракционы","vacation": "Отдых"},
    "Home": {"hotels_title": "Роскошные отели","villas_title": "Виллы","apartments_title": "Апартаменты","recommended_title": "Наши рекомендации","view_all": "Смотреть все"},
    "SearchForm": {"property_type": "Тип объекта","location": "Местоположение","dates": "Даты","guests": "Гости","search_btn": "Найти отдых","check_in": "Заезд","check_out": "Выезд","select_dates": "Выберите даты","confirm": "Подтвердить","close": "Закрыть","ai_mode": "Поиск с ИИ","standard_mode": "Стандартный поиск","ai_placeholder": "Опишите отпуск своей мечты...","thinking": "Думаем...","magic_search": "Магический поиск","types": {"all": "Все","hotel": "Отели","apartment": "Квартиры","villa": "Виллы"}},
    "Auth": {"login_title": "С возвращением","login_subtitle": "Войдите в аккаунт","register_title": "Регистрация","register_subtitle": "Выберите тип аккаунта","email": "Эл. почта","password": "Пароль","full_name": "Полное имя","login_btn": "Войти","register_btn": "Создать аккаунт","no_account": "Нет аккаунта?","has_account": "Уже есть аккаунт?","sign_up": "Регистрация","login": "Войти","role_guest": "Я хочу забронировать","role_host": "Я хочу сдавать","role_guest_desc": "Клиент","role_host_desc": "Владелец","welcome": "Привет","logout": "Выйти","my_account": "Мой аккаунт","business_dashboard": "Бизнес-панель","admin_panel": "Панель админа","login_link": "Вход","account_menu_label": "Вход в аккаунт","login_gateway_title": "Кто вы?","login_gateway_subtitle": "Выберите тип входа","login_admin_title": "Вход для админа","login_admin_subtitle": "Доступ","login_host_title": "Вход для владельца","login_host_subtitle": "Управление объектами","login_customer_title": "Вход для клиента","login_customer_subtitle": "Просмотр бронирований","list_asset": "Разместить объект"},
    "Host": {"hero_title": "Присоединяйтесь к нам","hero_subtitle": "Сделайте свой объект лучшим в Эйлате.","form_title": "Начните свой путь","form_subtitle": "Заполните детали, и мы свяжемся с вами в течение 24 часов.","first_name": "Имя","last_name": "Фамилия","property_type": "Тип объекта","phone": "Телефон","submit": "Отправить","benefits": {"earn_title": "Зарабатывайте больше","earn_desc": "Сохраняйте до 90% долей дохода.","protection_title": "Полная защита","protection_desc": "Страхование хозяев на 1 000 000 шек.","guests_title": "Качественные гости","guests_desc": "Мы привлекаем качественную аудиторию.","manage_title": "Простое управление","manage_desc": "ИИ система для простого управления."},"types": {"villa": "Вилла","penthouse": "Пентхаус","hotel": "Бутик-отель","other": "Другое"},"add_property_title": "Добавить объект","add_property_subtitle": "Заполните данные для публикации","basic_info": "Общая информация","property_title": "Название объекта","price_per_night": "Цена за ночь","description": "Описание объекта","photos": "Фотографии","upload_click": "Загрузить фото","cancel": "Отмена","publish": "Опубликовать","processing": "Сохранение..."},
    "Footer": {"quick_links": "Быстрые ссылки","support": "Поддержка и профиль","contact_us": "Связаться с нами","newsletter_placeholder": "Ваш email...","newsletter_btn": "Подписаться","rights": "Все права защищены."},
    "Accessibility": {"enlarge_text": "Увеличить текст","decrease_text": "Уменьшить текст","high_contrast": "Высокая контрастность","monochrome": "Монохром","readable_font": "Читаемый шрифт","highlight_links": "Выделить ссылки","stop_animations": "Остановить анимацию","reset": "Сбросить настройки"},
    "Cart": {"title": "Ваша корзина","empty": "Корзина пуста","sold_out": "Распродано!","per_night": "ночь","view_property": "Просмотр объекта","total": "Итого:","proceed": "К оплате","clear": "Очистить корзину","added": "Добавлено","save_later": "Сохранить на потом"},
    "Deals": {"last_minute": "Скидка до 25% на выходные!"},
    "Experiences": {"title": "Незабываемые впечатления","subtitle": "Специальные аттракционы по эксклюзивным ценам для вас."},
    "OnlineChat": {"live_chat": "Онлайн Чат","voice_on": "Включить голос","voice_off": "Выключить голос","stop_audio": "Остановить аудио","whatsapp": "Перейти в WhatsApp","call_management": "Связаться с руководством"},
    "Calendar": {"next": "Следующий","previous": "Предыдущий","today": "Сегодня","month": "Месяц","week": "Неделя","day": "День"},
    "Reviews": {"name_placeholder": "Ваше имя...","review_placeholder": "Расскажите, как прошел отпуск...","submit": "Отправить отзыв"}
};

const fr = {
    ...en,
    "Metadata": {"title": "Eilat Booking Premium - Vacances de luxe à Eilat","description": "Réservez vos prochaines vacances à Eilat dans les appartements les plus luxueux."},
    "Navigation": {"home": "Accueil","apartments": "Appartements","hotels": "Hôtels de Luxe","villas": "Villas","experiences": "Expériences","magazine": "Magazine","vip": "Services VIP","about": "À propos","contact": "Contact","search": "Recherche","accessibility": "Accessibilité","profile": "Profil"},
    "Hero": {"title": "Hospitalité de luxe à Eilat","subtitle": "Appartements de vacances exclusifs","cta": "Réservez"},
    "Featured": {"title": "Nos offres vedettes","subtitle": "Choisissez parmi notre collection exclusive","night": "nuit","book": "Réserver","details": "Plus de détails","guests": "Invités","rooms": "Chambres","recommended": "Recommandé"},
    "Property": {"about": "À propos","location": "Localisation","waze": "Naviguer avec Waze","amenities": "Équipements","guests": "Invités","guests_max": "Max","rooms": "Chambres","bedrooms": "Chambres à coucher","per_night": "Par nuit","book_now": "Réserver","total_price": "Prix Total","taxes": "Taxes incluses","not_charged": "Vous ne serez pas débité"},
    "Checkout": {"title": "Paiement Sécurisé","confirm": "Confirmer et Payer","booking_for": "Réservation pour","dates": "Dates","guests": "Invités","total": "Total à payer","service_fee": "Frais de service","back": "Retour"},
    "Payment": {"card_name": "Nom de la carte","card_number": "Numéro de la carte","expiry": "Expiration","cvc": "CVC","pay": "Payer","processing": "Traitement...","success_title": "Paiement Réussi!","success_msg": "Votre réservation est confirmée.","secure": "Paiement Sécurisé SSL","or_card": "Ou payer par carte"},
    "Search": {"title": "Résultats de recherche","view_all": "Voir tout"},
    "Categories": {"title": "Vacances par Catégorie","hotels": "Hôtels","apartments": "Appartements","villas": "Villas","attractions": "Attractions","vacation": "Vacances"},
    "Home": {"hotels_title": "Hôtels de Luxe","villas_title": "Villas","apartments_title": "Appartements","recommended_title": "Nos Recommandations","view_all": "Voir tout"},
    "SearchForm": {"property_type": "Type de propriété","location": "Localisation","dates": "Dates","guests": "Invités","search_btn": "Rechercher","check_in": "Arrivée","check_out": "Départ","select_dates": "Sélectionnez des dates","confirm": "Confirmer","close": "Fermer","ai_mode": "Recherche IA Intelligente","standard_mode": "Recherche Standard","ai_placeholder": "Décrivez vos vacances de rêve...","thinking": "Réflexion...","magic_search": "Recherche Magique","types": {"all": "Tout","hotel": "Hôtels","apartment": "Apprt.","villa": "Villas"}},
    "Auth": {"login_title": "Bon retour","login_subtitle": "Connectez-vous à votre compte","register_title": "Rejoignez-nous","register_subtitle": "Choisissez le type de compte","email": "E-mail","password": "Mot de passe","full_name": "Nom complet","login_btn": "Connexion","register_btn": "Créer un compte","no_account": "Pas de compte?","has_account": "Déjà un compte?","sign_up": "S'inscrire","login": "Connexion","role_guest": "Je veux réserver","role_host": "Je veux héberger","role_guest_desc": "Client","role_host_desc": "Propriétaire","welcome": "Bonjour","logout": "Se déconnecter","my_account": "Mon Compte","business_dashboard": "Tableau de Bord","admin_panel": "Panneau d'administration","login_link": "Se Connecter","account_menu_label": "Connexion au compte","login_gateway_title": "Qui êtes-vous?","login_gateway_subtitle": "Choisissez votre type de connexion","login_admin_title": "Connexion Admin","login_admin_subtitle": "Accès Admin","login_host_title": "Connexion Propriétaire","login_host_subtitle": "Gérez vos propriétés","login_customer_title": "Connexion Client","login_customer_subtitle": "Vos réservations","list_asset": "Inscrire"},
    "Host": {"hero_title": "Devenez un Hôte","hero_subtitle": "Transformez votre propriété en une destination prisée.","form_title": "Commencez votre aventure","form_subtitle": "Remplissez les détails et nous vous contacterons.","first_name": "Prénom","last_name": "Nom","property_type": "Type de propriété","phone": "Téléphone","submit": "Soumettre la demande","benefits": {"earn_title": "Gagnez plus","earn_desc": "Conservez jusqu'à 90 % de vos revenus.","protection_title": "Protection totale","protection_desc": "Assurance de 1 000 000 ILS par réservation.","guests_title": "Invités de qualité","guests_desc": "Nous attirons un public recherchant le luxe.","manage_title": "Gestion facile","manage_desc": "Système IA avancé pour tout gérer facilement."},"types": {"villa": "Villa","penthouse": "Attique","hotel": "Hôtel de charme","other": "Autre"},"add_property_title": "Ajouter Propriété","add_property_subtitle": "Remplissez les informations","basic_info": "Infos Générales","property_title": "Titre","price_per_night": "Prix par nuit","description": "Description","photos": "Photos","upload_click": "Télécharger Photos","cancel": "Annuler","publish": "Publier","processing": "Enregistrement..."},
    "Footer": {"quick_links": "Liens Rapides","support": "Support & Compte","contact_us": "Contactez-nous","newsletter_placeholder": "Votre Email...","newsletter_btn": "S'abonner","rights": "Tous droits réservés."},
    "Accessibility": {"enlarge_text": "Agrandir le texte","decrease_text": "Réduire le texte","high_contrast": "Contraste Élevé","monochrome": "Monochrome","readable_font": "Police Lisible","highlight_links": "Mettre en Évidence","stop_animations": "Arrêter les Animations","reset": "Réinitialiser"},
    "Cart": {"title": "Votre Panier","empty": "Le panier est vide","sold_out": "Épuisé!","per_night": "Nuit","view_property": "Voir la Propriété","total": "Total:","proceed": "Passer à la Caisse","clear": "Vider le Panier","added": "Ajouté","save_later": "Enregistrer pour plus tard"},
    "Deals": {"last_minute": "Jusqu'à 25% de réduction ce week-end!"},
    "Experiences": {"title": "Expériences Inoubliables","subtitle": "Attractions et expériences exclusives à Eilat."},
    "OnlineChat": {"live_chat": "Chat en ligne","voice_on": "Voix Activée","voice_off": "Voix Désactivée","stop_audio": "Arrêter l'Audio","whatsapp": "Ouvrir WhatsApp","call_management": "Contacter la direction"},
    "Calendar": {"next": "Suivant","previous": "Précédent","today": "Aujourd'hui","month": "Mois","week": "Semaine","day": "Jour"},
    "Reviews": {"name_placeholder": "Votre nom...","review_placeholder": "Racontez-nous vos vacances...","submit": "Envoyer"}
};

const ar = {
    ...en,
    "Metadata": {"title": "إيلات بوكينج بريميوم - عطلات فاخرة في إيلات","description": "احجز عطلتك القادمة في أفضل شقق العطلات الفاخرة في إيلات."},
    "Navigation": {"home": "الرئيسية","apartments": "شقق","hotels": "فنادق فاخرة","villas": "فيلات","experiences": "تجارب","magazine": "مجلة","vip": "خدمات VIP","about": "حول","contact": "اتصل بنا","search": "بحث","accessibility": "سهولة الوصول","profile": "الملف الشخصي"},
    "Hero": {"title": "ضيافة فاخرة في إيلات","subtitle": "شقق عطلات حصرية في أفضل المواقع","cta": "احجز الان"},
    "Featured": {"title": "عقاراتنا المميزة","subtitle": "اختر من مجموعتنا الحصرية للعطلة المثالية","night": "ليلة","book": "احجز الان","details": "المزيد من التفاصيل","guests": "الضيوف","rooms": "غرف","recommended": "موصى به"},
    "Property": {"about": "حول العقار","location": "الموقع","waze": "توجيه باستخدام Waze","amenities": "المرافق","guests": "الضيوف","guests_max": "الحد الأقصى","rooms": "غرف","bedrooms": "غرف نوم","per_night": "في الليلة","book_now": "احجز الان","total_price": "السعر الإجمالي","taxes": "شامل الضرائب والرسوم","not_charged": "لن يتم الخصم بعد"},
    "Checkout": {"title": "دفع آمن","confirm": "تأكيد ودفع","booking_for": "حجزك لـ","dates": "التواريخ","guests": "الضيوف","total": "المجموع للدفع","service_fee": "رسوم الخدمة","back": "عودة"},
    "Payment": {"card_name": "اسم صاحب البطاقة","card_number": "رقم البطاقة","expiry": "تاريخ الانتهاء","cvc": "CVC","pay": "دفع","processing": "جاري المعالجة...","success_title": "اكتمل الدفع بنجاح!","success_msg": "تم تأكيد حجزك. تم إرسال إيصال.","secure": "دفع آمن SSL","or_card": "أو ادفع بالبطاقة"},
    "Search": {"title": "نتائج البحث","view_all": "عرض الكل"},
    "Categories": {"title": "عطلات حسب الفئة","hotels": "فنادق فاخرة","apartments": "شقق عطلات","villas": "فيلات حصرية","attractions": "مناطق جذب","vacation": "عطلة"},
    "Home": {"hotels_title": "فنادق فاخرة","villas_title": "فيلات حصرية","apartments_title": "شقق عطلات","recommended_title": "توصياتنا","view_all": "عرض الكل"},
    "SearchForm": {"property_type": "نوع العقار","location": "الموقع","dates": "التواريخ","guests": "الضيوف","search_btn": "ابحث عن عطلة","check_in": "تسجيل الدخول","check_out": "تسجيل الخروج","select_dates": "اختر التواريخ","confirm": "تأكيد","close": "إغلاق","ai_mode": "بحث ذكي بالذكاء الاصطناعي","standard_mode": "بحث قياسي","ai_placeholder": "صف عطلة أحلامك... (مثل: 'فيلا فاخرة لـ 10 أشخاص مع مسبح')","thinking": "يفكر...","magic_search": "بحث سحري","types": {"all": "الكل","hotel": "فنادق","apartment": "شقق","villa": "فيلات"}},
    "Auth": {"login_title": "مرحباً بعودتك","login_subtitle": "قم بتسجيل الدخول لحسابك","register_title": "انضم إلينا","register_subtitle": "اختر نوع الحساب","email": "البريد الإلكتروني","password": "كلمة المرور","full_name": "الاسم الكامل","login_btn": "دخول","register_btn": "إنشاء حساب","no_account": "ليس لديك حساب؟","has_account": "هل لديك حساب بالفعل؟","sign_up": "تسجيل","login": "تسجيل الدخول","role_guest": "أريد الحجز","role_host": "أريد الاستضافة","role_guest_desc": "عميل","role_host_desc": "صاحب عمل","welcome": "مرحباً","logout": "تسجيل الخروج","my_account": "حسابي","business_dashboard": "لوحة الأعمال","admin_panel": "لوحة الإدارة","login_link": "دخول","account_menu_label": "دخول الحساب","login_gateway_title": "من أنت؟","login_gateway_subtitle": "اختر نوع الدخول","login_admin_title": "دخول الإدارة","login_admin_subtitle": "الوصول للإدارة","login_host_title": "دخول المضيف","login_host_subtitle": "إدارة العقارات","login_customer_title": "دخول العميل","login_customer_subtitle": "عرض الحجوزات","list_asset": "إدراج عقار"},
    "Host": {"hero_title": "انضم إلى مضيفينا","hero_subtitle": "اجعل عقارك الوجهة القادمة.","form_title": "ابدأ رحلتك","form_subtitle": "املأ التفاصيل وسنتواصل معك.","first_name": "الاسم","last_name": "العائلة","property_type": "نوع العقار","phone": "الهاتف","submit": "إرسال","benefits": {"earn_title": "اربح المزيد","earn_desc": "احتفظ بـ 90٪ من أرباحك.","protection_title": "حماية كاملة","protection_desc": "تأمين بقيمة 1,000,000 شيكل.","guests_title": "ضيوف متميزون","guests_desc": "نجذب جمهورًا يبحث عن الفخامة.","manage_title": "إدارة سهلة","manage_desc": "نظام ذكاء اصطناعي لسهولة الإدارة."},"types": {"villa": "فيلا","penthouse": "بنتهاوس","hotel": "فندق بوتيك","other": "أخرى"},"add_property_title": "إضافة عقار","add_property_subtitle": "املأ التفاصيل للنشر","basic_info": "تفاصيل عامة","property_title": "العنوان","price_per_night": "السعر لليلة","description": "الوصف","photos": "صور","upload_click": "رفع صور","cancel": "إلغاء","publish": "نشر","processing": "جاري الحفظ..."},
    "Footer": {"quick_links": "روابط سريعة","support": "الدعم والحساب","contact_us": "اتصل بنا","newsletter_placeholder": "البريد الإلكتروني...","newsletter_btn": "اشتراك","rights": "جميع الحقوق محفوظة."},
    "Accessibility": {"enlarge_text": "تكبير النص","decrease_text": "تصغير النص","high_contrast": "تباين عالٍ","monochrome": "ألوان أحادية","readable_font": "خط قابل للقراءة","highlight_links": "إبراز الروابط","stop_animations": "إيقاف الرسوم المتحركة","reset": "إعادة تعيين"},
    "Cart": {"title": "عربتك","empty": "العربة فارغة","sold_out": "نفد الكمية!","per_night": "ليلة","view_property": "عرض العقار","total": "المجموع:","proceed": "الذهاب للدفع","clear": "إفراغ العربة","added": "تمت الإضافة","save_later": "حفظ لوقت لاحق"},
    "Deals": {"last_minute": "خصم حتى 25٪ على إجازة نهاية الأسبوع القادمة!"},
    "Experiences": {"title": "تجارب لا تُنسى","subtitle": "عطلتك هي أكثر من مجرد نوم. لقد جمعنا لك أفضل المعالم والتجارب في إيلات، بأسعار حصرية."},
    "OnlineChat": {"live_chat": "دردشة مباشرة","voice_on": "تشغيل الصوت","voice_off": "كتم الصوت","stop_audio": "إيقاف الصوت","whatsapp": "الانتقال إلى واتساب","call_management": "الاتصال بالإدارة"},
    "Calendar": {"next": "التالي","previous": "السابق","today": "اليوم","month": "شهر","week": "أسبوع","day": "يوم"},
    "Reviews": {"name_placeholder": "اسمك...","review_placeholder": "أخبرنا كيف كانت العطلة...","submit": "إرسال التقييم"}
};

fs.writeFileSync(path.join(__dirname, 'locales/en.json'), JSON.stringify(en, null, 2), 'utf8');
fs.writeFileSync(path.join(__dirname, 'locales/he.json'), JSON.stringify(he, null, 2), 'utf8');
fs.writeFileSync(path.join(__dirname, 'locales/ru.json'), JSON.stringify(ru, null, 2), 'utf8');
fs.writeFileSync(path.join(__dirname, 'locales/fr.json'), JSON.stringify(fr, null, 2), 'utf8');
fs.writeFileSync(path.join(__dirname, 'locales/ar.json'), JSON.stringify(ar, null, 2), 'utf8');

console.log("Translation dictionaries synchronized successfully.");
