export type PropertyType = 'hotel' | 'apartment' | 'villa';

export interface Property {
    id: string;
    type: PropertyType;
    title: string;
    location: string;
    price: number;
    rating: number;
    guests: number;
    rooms: number;
    image: string;
    images: string[];
    description: string;
    amenities: string[];
}

export const properties: Property[] = [
    // --- HOTELS ---
    {
        id: 'h1',
        type: 'hotel',
        title: 'Royal Beach Eilat',
        location: 'North Beach, Eilat',
        price: 1500,
        rating: 4.9,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2670&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945', 'https://images.unsplash.com/photo-1582719508461-905c673771fd'],
        description: 'Luxury hotel on the beach with private pool and spa.',
        amenities: ['Pool', 'Spa', 'Gym', 'WiFi', 'Breakfast']
    },
    {
        id: 'h2',
        type: 'hotel',
        title: 'Dan Eilat',
        location: 'North Beach, Eilat',
        price: 1800,
        rating: 4.8,
        guests: 3,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=2649&auto=format&fit=crop',
        images: [],
        description: 'Famous luxury hotel with water park and kids club.',
        amenities: ['Pool', 'Kids Club', 'WiFi', 'Beach Access']
    },
    {
        id: 'h3',
        type: 'hotel',
        title: 'Herods Palace',
        location: 'Marina, Eilat',
        price: 1400,
        rating: 4.7,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Historical themed palace hotel.',
        amenities: ['Pool', 'Dining', 'WiFi']
    },
    {
        id: 'h4',
        type: 'hotel',
        title: 'Aria Eilat',
        location: 'South Beach, Eilat',
        price: 1200,
        rating: 4.6,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Modern hotel with direct beach access.',
        amenities: ['Beach', 'Pool', 'Bar']
    },
    {
        id: 'h5',
        type: 'hotel',
        title: 'Queen of Sheba',
        location: 'North Beach, Eilat',
        price: 1350,
        rating: 4.7,
        guests: 4,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Experience royalty in this magnificent hotel.',
        amenities: ['Pool', 'Spa', 'Mall']
    },
    {
        id: 'h6',
        type: 'hotel',
        title: 'Isrotel Agamim',
        location: 'City Center, Eilat',
        price: 1100,
        rating: 4.8,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Chill atmosphere with rooms on the water.',
        amenities: ['Pool Access', 'Bar', 'Adults Only']
    },
    {
        id: 'h7',
        type: 'hotel',
        title: 'Vert Eilat',
        location: 'North Beach, Eilat',
        price: 1000,
        rating: 4.5,
        guests: 3,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1590073242678-cfe2f792f3c8?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Panoramic views of the Red Sea.',
        amenities: ['View', 'Pool', 'WiFi']
    },
    {
        id: 'h8',
        type: 'hotel',
        title: 'U Coral Beach',
        location: 'South Beach, Eilat',
        price: 1600,
        rating: 4.6,
        guests: 4,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'All inclusive resort for families.',
        amenities: ['All Inclusive', 'Beach', 'Entertainment']
    },
    {
        id: 'h9',
        type: 'hotel',
        title: 'Herbert Samuel',
        location: 'Coral Beach, Eilat',
        price: 2000,
        rating: 4.9,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1571896349842-6e5a48d88a03?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Exclusive boutique hotel.',
        amenities: ['Private Pool', 'Chef', 'WiFi']
    },
    {
        id: 'h10',
        type: 'hotel',
        title: 'Neptune Eilat',
        location: 'North Beach',
        price: 900,
        rating: 4.4,
        guests: 3,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=2674&auto=format&fit=crop',
        images: [],
        description: 'Classic hotel next to the mall.',
        amenities: ['Central', 'Pool', 'WiFi']
    },

    // --- APARTMENTS ---
    {
        id: 'a1',
        type: 'apartment',
        title: 'Luxury Marina Penthouse',
        location: 'Marina, Eilat',
        price: 1200,
        rating: 4.9,
        guests: 6,
        rooms: 3,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2560&auto=format&fit=crop',
        images: [],
        description: 'Stunning penthouse overlooking the marina.',
        amenities: ['Jacuzzi', 'Terrace', 'WiFi']
    },
    {
        id: 'a2',
        type: 'apartment',
        title: 'Sea View Loft',
        location: 'Shachamon, Eilat',
        price: 800,
        rating: 4.8,
        guests: 4,
        rooms: 2,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Modern loft with panoramic sea view.',
        amenities: ['View', 'Smart TV', 'Kitchen']
    },
    {
        id: 'a3',
        type: 'apartment',
        title: 'Beachfront Condo',
        location: 'North Beach',
        price: 1000,
        rating: 4.7,
        guests: 5,
        rooms: 2,
        image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Steps away from the beach.',
        amenities: ['Pool', 'Gym', 'Parking']
    },
    {
        id: 'a4',
        type: 'apartment',
        title: 'Cozy Garden Flat',
        location: 'Roded, Eilat',
        price: 500,
        rating: 4.5,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1502005229766-939cb9342722?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Quiet garden apartment.',
        amenities: ['Garden', 'BBQ', 'WiFi']
    },
    {
        id: 'a5',
        type: 'apartment',
        title: 'Royal Park Suite',
        location: 'North Beach',
        price: 700,
        rating: 4.6,
        guests: 4,
        rooms: 2,
        image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Family suite in Royal Park.',
        amenities: ['Pool', 'Playground', 'Kitchen']
    },
    {
        id: 'a6',
        type: 'apartment',
        title: 'Golf Residence Info',
        location: 'Roded, Eilat',
        price: 600,
        rating: 4.7,
        guests: 3,
        rooms: 2,
        image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Modern apartment in luxury complex.',
        amenities: ['Pool', 'Sauna', 'Gym']
    },
    {
        id: 'a7',
        type: 'apartment',
        title: 'Lagoon Duplex',
        location: 'Marina, Eilat',
        price: 1300,
        rating: 4.9,
        guests: 7,
        rooms: 3,
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Huge duplex on the lagoon water.',
        amenities: ['Waterfront', 'Terrace', 'Smart Home']
    },
    {
        id: 'a8',
        type: 'apartment',
        title: 'Sunset Studio',
        location: 'Shachamon',
        price: 400,
        rating: 4.5,
        guests: 2,
        rooms: 1,
        image: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365?q=80&w=2564&auto=format&fit=crop',
        images: [],
        description: 'Perfect for couples. Sunset views.',
        amenities: ['View', 'WiFi', 'Kitchenette']
    },
    {
        id: 'a9',
        type: 'apartment',
        title: 'City Center Hub',
        location: 'City Center',
        price: 550,
        rating: 4.6,
        guests: 3,
        rooms: 2,
        image: 'https://images.unsplash.com/photo-1484154218962-a1c002085d2f?q=80&w=2671&auto=format&fit=crop',
        images: [],
        description: 'Close to everything.',
        amenities: ['Central', 'Balcony', 'WiFi']
    },
    {
        id: 'a10',
        type: 'apartment',
        title: 'Amber Residence',
        location: 'Amber, Eilat',
        price: 900,
        rating: 4.8,
        guests: 5,
        rooms: 3,
        image: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'High floor residence with pool.',
        amenities: ['Pool', 'Parking', 'View']
    },

    // --- VILLAS ---
    {
        id: 'v1',
        type: 'villa',
        title: 'Grand Royal Villa',
        location: 'Villas Neighborhood',
        price: 3000,
        rating: 5.0,
        guests: 12,
        rooms: 6,
        image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'The ultimate luxury villa in Eilat.',
        amenities: ['Heated Pool', 'Cinema', 'Chef Kitchen']
    },
    {
        id: 'v2',
        type: 'villa',
        title: 'Desert Oasis Villa',
        location: 'Roded, Eilat',
        price: 2500,
        rating: 4.9,
        guests: 10,
        rooms: 5,
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Secluded villa with desert views.',
        amenities: ['Infinity Pool', 'Privacy', 'BBQ']
    },
    {
        id: 'v3',
        type: 'villa',
        title: 'White House Eilat',
        location: 'Ganim B',
        price: 2800,
        rating: 4.8,
        guests: 10,
        rooms: 5,
        image: 'https://images.unsplash.com/photo-1600596542815-6ad4c728fdbe?q=80&w=2675&auto=format&fit=crop',
        images: [],
        description: 'Modern white architecture villa.',
        amenities: ['Pool', 'Game Room', 'Jacuzzi']
    },
    {
        id: 'v4',
        type: 'villa',
        title: 'Palm Villa',
        location: 'Shachamon',
        price: 2200,
        rating: 4.7,
        guests: 8,
        rooms: 4,
        image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?q=80&w=2574&auto=format&fit=crop',
        images: [],
        description: 'Tropical garden villa.',
        amenities: ['Garden', 'Pool', 'Pizza Oven']
    },
    {
        id: 'v5',
        type: 'villa',
        title: 'Blue Horizon Villa',
        location: 'Shachamon',
        price: 2600,
        rating: 4.9,
        guests: 12,
        rooms: 6,
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Overlooking the bay.',
        amenities: ['View', 'Pool', 'Events Allowed']
    },
    {
        id: 'v6',
        type: 'villa',
        title: 'Villa 777',
        location: 'Villas Neighborhood',
        price: 3500,
        rating: 5.0,
        guests: 14,
        rooms: 7,
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2653&auto=format&fit=crop',
        images: [],
        description: 'Huge villa for large groups.',
        amenities: ['Karaoke', 'Pool', 'Jacuzzi']
    },
    {
        id: 'v7',
        type: 'villa',
        title: 'Zen Luxury Villa',
        location: 'Roded',
        price: 2400,
        rating: 4.8,
        guests: 8,
        rooms: 4,
        image: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'Japanese style calm villa.',
        amenities: ['Zen Garden', 'Pool', 'Sauna']
    },
    {
        id: 'v8',
        type: 'villa',
        title: 'Party Villa Eilat',
        location: 'Industrial Area',
        price: 2000,
        rating: 4.5,
        guests: 15,
        rooms: 5,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=2632&auto=format&fit=crop',
        images: [],
        description: 'Perfect for bachelor parties.',
        amenities: ['Sound System', 'Pool', 'No Noise Limit']
    },
    {
        id: 'v9',
        type: 'villa',
        title: 'Family Retreat Villa',
        location: 'Ganim A',
        price: 2300,
        rating: 4.7,
        guests: 10,
        rooms: 5,
        image: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=2525&auto=format&fit=crop',
        images: [],
        description: 'Features for kids and relaxation.',
        amenities: ['Pool Fence', 'Toys', 'Space']
    },
    {
        id: 'v10',
        type: 'villa',
        title: 'The Mansion',
        location: 'Villas Neighborhood',
        price: 5000,
        rating: 5.0,
        guests: 20,
        rooms: 10,
        image: 'https://images.unsplash.com/photo-1510627489930-0c1b0dc58e85?q=80&w=2670&auto=format&fit=crop',
        images: [],
        description: 'The biggest villa in town.',
        amenities: ['Everything', 'Butler', 'Cinema']
    }
];
