import { getTranslations } from 'next-intl/server';
import { properties as rawProperties } from '@/lib/mock-data';
import { translateProperties } from '@/lib/translate-mock';
import { notFound } from 'next/navigation';
import Image from 'next/image';
import { MapPin, Users, Bed, Wifi, Star, Check } from 'lucide-react';
import { Link } from '@/navigation';
import AddToCartButton from '@/components/features/add-to-cart';
import ReviewsSection from '@/components/features/reviews-section';
import AvailabilityCalendar from '@/components/features/availability-calendar';
import LocationMap from '@/components/features/location-map';
import BookingInteractiveSection from '@/components/features/booking-interactive-section';
import dbConnect from '@/lib/db';
import Property from '@/models/Property';
import type { Metadata } from 'next';

export async function generateMetadata(
    { params }: { params: Promise<{ id: string, locale: string }> }
): Promise<Metadata> {
    const { id, locale } = await params;
    const properties = translateProperties(rawProperties, locale);

    // Fallbacks
    let title = "Property | Eilat Booking Premium";
    let description = "Luxury vacation rental in Eilat.";
    let image = "/og-image.jpg";

    let property = properties.find(p => p.id === id);

    if (!property && id.match(/^[0-9a-fA-F]{24}$/)) {
        try {
            await dbConnect();
            const doc = await Property.findById(id).lean();
            if (doc) {
                title = `${doc.title} | Eilat Booking Premium`;
                description = doc.description || description;
                image = (doc.images && doc.images[0]) || image;
            }
        } catch (e) {
            console.error(e);
        }
    } else if (property) {
        title = `${property.title} | Eilat Booking Premium`;
        description = property.description;
        image = property.image;
    }

    return {
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            images: [{ url: image }],
        },
        twitter: {
            card: "summary_large_image",
            title: title,
            description: description,
            images: [image],
        }
    };
}

export default async function PropertyPage(props: { params: Promise<{ id: string, locale: string }> }) {
    const params = await props.params;
    const { id, locale } = params;
    const t = await getTranslations({ locale, namespace: 'Property' });
    const properties = translateProperties(rawProperties, locale);

    // 1. Try fetching from Mock Data first (Legacy/Static)
    let property = properties.find(p => p.id === params.id);

    // 2. If not found, try MongoDB (Dynamic)
    if (!property) {
        try {
            // Check if ID is a valid MongoDB ObjectId
            if (params.id.match(/^[0-9a-fA-F]{24}$/)) {
                await dbConnect();
                const doc = await Property.findById(params.id).lean();

                if (doc) {
                    property = {
                        id: doc._id.toString(),
                        title: doc.title,
                        description: doc.description,
                        price: Number(doc.price),
                        location: doc.location || 'Eilat',
                        image: (doc.images && doc.images[0]) || 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                        images: doc.images || [],
                        amenities: doc.amenities || [],
                        rating: Number(doc.rating) || 0,
                        guests: doc.guests || 2,
                        rooms: doc.rooms || 1,
                        type: doc.type,
                        virtualTourUrl: doc.virtualTourUrl
                    };
                }
            }
        } catch (e) {
            console.error("MongoDB Fetch Error in Property Page", e);
        }
    }

    // 3. Fallback for "demo_" IDs generated by the upload fallback but not saved
    if (!property && params.id.startsWith('demo_')) {
        // Show a generic placeholder property so the user sees *something* instead of 404
        property = {
            ...properties[0],
            id: params.id,
            title: "Demo Property (Preview)",
            description: "This is a preview of a property that was created in Demo Mode. Real data persistence requires database configuration.",
            location: "Eilat (Demo)",
            price: 999
        };
    }

    if (!property) {
        notFound();
    }

    // ... (rest of filtering)

    return (
        <main className="min-h-screen bg-background text-foreground pt-24 pb-20 transition-colors duration-300">
            <div className="max-w-[1120px] mx-auto px-4">
                {/* Header */}
                <div className="flex flex-col md:flex-row justify-start items-start md:items-end mb-8 gap-4 md:gap-24">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <span className="bg-primary text-black text-xs font-bold px-2 py-1 rounded uppercase">
                                {property.type}
                            </span>
                            <div className="flex items-center gap-1 text-primary">
                                <Star size={14} fill="currentColor" />
                                <span className="font-bold text-sm">{property.rating}</span>
                            </div>
                        </div>
                        <h1 className="text-3xl md:text-5xl font-bold mb-2">{property.title}</h1>
                        <div className="flex items-center gap-2 text-muted-foreground">
                            <MapPin size={18} />
                            <span>{property.location}</span>
                        </div>
                    </div>
                    <div className="text-right">
                        <div className="text-3xl font-bold text-primary">₪{property.price}</div>
                        <div className="text-muted-foreground text-sm">{t('per_night')}</div>
                    </div>
                </div>

                {/* Gallery */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 h-[400px] md:h-[500px] mb-12 rounded-2xl overflow-hidden">
                    <div className="md:col-span-2 relative h-full">
                        <Image
                            src={property.image}
                            alt={property.title}
                            fill
                            className="object-cover hover:scale-105 transition-transform duration-700"
                        />
                    </div>
                    <div className="hidden md:flex flex-col gap-4 h-full">
                        {property.images && property.images.length > 0 ? (
                            property.images.slice(0, 2).map((img, i) => (
                                <div key={i} className="relative flex-1 rounded-xl overflow-hidden">
                                    <Image src={img} alt="Gallery" fill className="object-cover" />
                                </div>
                            ))
                        ) : (
                            // Fallback if no gallery images
                            <>
                                <div className="relative flex-1 rounded-xl overflow-hidden bg-muted" />
                                <div className="relative flex-1 rounded-xl overflow-hidden bg-muted" />
                            </>
                        )}
                    </div>
                </div>

                {/* Content */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
                    {/* Left: Description & Amenities */}
                    <div className="lg:col-span-2">
                        <h2 className="text-2xl font-bold mb-4">{t('about')}</h2>
                        <p className="text-muted-foreground leading-relaxed mb-8 text-lg text-right" dir="rtl">
                            {property.description}
                        </p>

                        <h3 className="text-xl font-bold mb-4">{t('amenities')}</h3>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-12">
                            {property.amenities.map(am => (
                                <div key={am} className="flex items-center gap-3 bg-card border border-border p-4 rounded-xl shadow-sm">
                                    <Check size={18} className="text-primary" />
                                    <span>{am}</span>
                                </div>
                            ))}
                        </div>

                        <div className="flex gap-8 border-t border-border pt-8">
                            <div className="flex items-center gap-3">
                                <div className="bg-muted p-3 rounded-full">
                                    <Users size={24} />
                                </div>
                                <div>
                                    <div className="text-sm text-muted-foreground">{t('guests')}</div>
                                    <div className="font-bold">{property.guests} {t('guests_max')}</div>
                                </div>
                            </div>
                            <div className="flex items-center gap-3">
                                <div className="bg-muted p-3 rounded-full">
                                    <Bed size={24} />
                                </div>
                                <div>
                                    <div className="text-sm text-muted-foreground">{t('rooms')}</div>
                                    <div className="font-bold">{property.rooms} {t('bedrooms')}</div>
                                </div>
                            </div>
                    </div>
                </div>

                <BookingInteractiveSection 
                    property={property} 
                    tLabels={{
                        availability: t('availability'),
                        total_price: t('total_price'),
                        taxes: t('taxes'),
                        book_now: t('book_now'),
                        not_charged: t('not_charged')
                    }}
                />
                </div>

                {/* Reviews Section */}
                <ReviewsSection propertyId={property.id} />
            </div>
        </main>
    );
}
